### ISSUE TITLE
[REQUEST]: Document how to enable agentless support in an integration

### ISSUE THREAD

**Issue by jsoriano** [elastic/ingest-docs#1031]
### Description

We are adding support for "agentless" in integrations. These integrations will be deployed in fully managed agents, so the way they are configured will be slightly different.

We should document somewhere the related features:
* The concept of deployment mode, introduced in https://github.com/elastic/package-spec/pull/738.
* Enabling agentless in template policies in packages, for example:
```
...
policy_templates:
  - name: billing
    title: AWS Billing
    description: Collect billing metrics with Elastic Agent
    deployment_modes:
      agentless:
        enabled: true
...
```
* Disabling variables if needed:
```
        hide_in_deployment_modes:
          - agentless
```
* Capabilities in the agentless-controller: https://github.com/elastic/agentless-controller/blob/add8018ff3bfc04de64c0eb057eabd4937a0bbad/controllers/config/capabilities.yml

### Resources

Meta issue: https://github.com/elastic/ingest-dev/issues/3013
Package Spec design issue: https://github.com/elastic/package-spec/issues/684

### Collaboration

TBD. The docs and product team will work together to determine the best path forward.

### Point of contact.

**Main contact:** @kpollich 

**Stakeholders:** @jsoriano @nima
