### ISSUE TITLE
[Request]: Update "Define deployment modes" page to have filestream example

### ISSUE THREAD

**Issue by qcorporation** [elastic/ingest-docs#1286]
### Description

The filebeat's [log input](https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-input-log.html) which was deprecated in favor of the [filestream input](https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-input-filestream.html) in 7.16 should also be reflected within the example documentation to make sure that if/when we remove logfile support ([potentially in 9.0](https://github.com/elastic/ingest-dev/issues/1107)) 
The example in question starts here:
location: https://github.com/elastic/observability-docs/blob/363af381dc2de59051fcf4af78937c8f47bf202a/docs/en/integrations/build-integration.asciidoc?plain=1#L189

We need to give a more modern example for filestream so that any new development won't steer contributions into integration to a deprecated mode of operation

### Resources

You can use the filestream [documentation](https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-input-filestream.html) to help formulate a proper example variable declaration

### Which documentation set does this change impact?

Integrations

### Feature differences

This is a part of integrations and is just an update to a legacy integration practice.

### What release is this request related to?

N/A

### Collaboration model

The documentation team

### Point of contact.

**Main contact:** @qcorporation

**Comment by kilfoyle** [comment]
@jlind23  Is there a developer who might be able to provide a new version of the [hide_in_deployment_modes](https://www.elastic.co/guide/en/integrations-developer/current/define-deployment-modes.html#hide_in_deployment_modes) example (from the Integrations Developer Guide) that uses filestream? I'm out of my element here. :-)

**Comment by jlind23** [comment]
@belimawr might probably be best to assists here.
cc @pierrehilbert

**Comment by belimawr** [comment]
@kilfoyle do you mean something like that:
```yaml
streams:
  - input: filestream
    vars:
      - name: paths
        type: text
        title: Paths
        multi: true
        required: true
        show_user: true
        default:
          - /var/log/my-package/*.log
      - name: agentless_only
        type: text
        title: Agentless only variable
        multi: false
        required: false
        show_user: true
        hide_in_deployment_modes: 
          - default
     - name: hidden_in_agentless
       type: text
       title: Hidden in agentless variable
       multi: false
       required: false
       show_user: true
       hide_in_deployment_modes: 
         - agentless
```

Or are you looking for something more specific?
