### ISSUE TITLE
Document deploying agent on K8s for none K8s monitoring usage

### ISSUE THREAD

**Issue by ThorbenJ** [elastic/ingest-docs#149]
Hi all,

We have many integrations that pull from various (cloud) APIs, as such one needs an Agent to run them on. (e.g. MISP, M365D, etc). However our how to deploy agent on k8s documentation assumes you are doing so to monitor k8s itself, thus we only document DaemonSet deployments. (e.g. https://www.elastic.co/guide/en/fleet/master/running-on-kubernetes-managed-by-fleet.html or https://www.elastic.co/guide/en/cloud-on-k8s/1.4/k8s-elastic-agent.html)

What if you just want an Agent to host integrations? You don't want or need DaemonSet, and probably shouldn't combine the two uses to the same policy and agents.

Please document the official supported way to deploy agent on k8s for remote or API based ingest. e.g. As a Deployment or perhaps a StatefulSet.

This is what I use, but its not official:
```
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ela-state-alpha
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi
  storageClassName: standard-rwo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: elastic-agent-alpha
  name: elastic-agent-alpha
#  namespace: ...
spec:
  # Do not scale beyond 1 unless all policy integrations support parallelism (e.g. Azure Event Hub ingest)
  replicas: 1
  selector:
    matchLabels:
      app: elastic-agent-alpha
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: elastic-agent-alpha
    spec:
      securityContext:
        runAsUser: 0
        runAsGroup: 0
      containers:
      - name: elastic-agent-alpha
        image: docker.elastic.co/beats/elastic-agent:8.6.2
        resources:
          limits:
            memory: 700Mi
          requests:
            cpu: 100m
            memory: 400Mi
        env:
        - name: FLEET_ENROLL
          value: "1"
        - name: FLEET_INSECURE
          value: "false"
        - name: FLEET_URL
          valueFrom:
            secretKeyRef:
              name: fleet-creds-alpha
              key: url
        - name: FLEET_ENROLLMENT_TOKEN
          valueFrom:
            secretKeyRef:
              name: fleet-creds-alpha
              key: token
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        volumeMounts:
        - name: ela-state-alpha
          mountPath: "/usr/share/elastic-agent/state"
      volumes:
      - name: ela-state-alpha
        persistentVolumeClaim:
          claimName: ela-state-alpha
# Create secret
# kcn create secret generic fleet-creds-alpha --from-literal=url="<URL>>" --from-literal=token="<TOKEN>"
# Duplicate for more agents to run other things
# for l in beta gamma delta epsilon zeta ; do sed -e "s/-alpha/-$l/g" < agent_alpha.yaml > agent_$l.yaml ; done
```

I've seen many broken customer agent deployment where they have tried to use our documentation to deploy Agent on k8s to have something to run their integrations on, they were not interested in k8s monitoring.

BR,
Thorben

**Comment by ThorbenJ** [comment]
Hi all, in order to support a customer (who I know is watching this issue) I've gone further down the rabbit hole...

# 1 (of 2):

We document deploying Agent on k8s as a DaemonSet (in both its own docs and in ECK docs) in order to monitor k8s itself. Assuming the customer wants to do, there is still the issue that Agent state is not preserved so pod restarts create a new agent and clutter the fleet UI.

In the end I did
```
# kate: replace-tabs on; indent-width 2; tab-width 8; indent-mode: normal; show-tabs on;
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: elastic-agent-k8smon
subjects:
  - kind: ServiceAccount
    name: elastic-agent-k8smon
    namespace: monitoring
roleRef:
  kind: ClusterRole
  name: elastic-agent-k8smon
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: monitoring
  name: elastic-agent-k8smon
subjects:
  - kind: ServiceAccount
    name: elastic-agent-k8smon
    namespace: monitoring
roleRef:
  kind: Role
  name: elastic-agent-k8smon
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: elastic-agent-kubeadm-config
  namespace: monitoring
subjects:
  - kind: ServiceAccount
    name: elastic-agent-k8smon
    namespace: monitoring
roleRef:
  kind: Role
  name: elastic-agent-kubeadm-config
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: elastic-agent-k8smon
  labels:
    k8s-app: elastic-agent-k8smon
rules:
  - apiGroups: [""]
    resources:
      - nodes
      - namespaces
      - events
      - pods
      - services
      - configmaps
      # Needed for cloudbeat
      - serviceaccounts
      - persistentvolumes
      - persistentvolumeclaims
    verbs: ["get", "list", "watch"]
  # Enable this rule only if planing to use kubernetes_secrets provider
  #- apiGroups: [""]
  #  resources:
  #  - secrets
  #  verbs: ["get"]
  - apiGroups: ["extensions"]
    resources:
      - replicasets
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources:
      - statefulsets
      - deployments
      - replicasets
      - daemonsets
    verbs: ["get", "list", "watch"]
  - apiGroups:
      - ""
    resources:
      - nodes/stats
    verbs:
      - get
  - apiGroups: [ "batch" ]
    resources:
      - jobs
      - cronjobs
    verbs: [ "get", "list", "watch" ]
  # Needed for apiserver
  - nonResourceURLs:
      - "/metrics"
    verbs:
      - get
  # Needed for cloudbeat
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources:
      - clusterrolebindings
      - clusterroles
      - rolebindings
      - roles
    verbs: ["get", "list", "watch"]
  # Needed for cloudbeat
  - apiGroups: ["policy"]
    resources:
      - podsecuritypolicies
    verbs: ["get", "list", "watch"]
  - apiGroups: [ "storage.k8s.io" ]
    resources:
      - storageclasses
    verbs: [ "get", "list", "watch" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: elastic-agent-k8smon
  # Should be the namespace where elastic-agent is running
  namespace: monitoring
  labels:
    k8s-app: elastic-agent-k8smon
rules:
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs: ["get", "create", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: elastic-agent-kubeadm-config
  namespace: monitoring
  labels:
    k8s-app: elastic-agent-k8smon
rules:
  - apiGroups: [""]
    resources:
      - configmaps
    resourceNames:
      - kubeadm-config
    verbs: ["get"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: elastic-agent-k8smon
  namespace: monitoring
  labels:
    k8s-app: elastic-agent-k8smon

#########################################################
---
# For more information https://www.elastic.co/guide/en/fleet/current/running-on-kubernetes-managed-by-fleet.html
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: elastic-agent-k8smon
  namespace: monitoring
  labels:
    app: elastic-agent-k8smon
spec:
  selector:
    matchLabels:
      app: elastic-agent-k8smon
  template:
    metadata:
      labels:
        app: elastic-agent-k8smon
    spec:
      # Tolerations are needed to run Elastic Agent on Kubernetes control-plane nodes.
      # Agents running on control-plane nodes collect metrics from the control plane components (scheduler, controller manager) of Kubernetes
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          effect: NoSchedule
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
      serviceAccountName: elastic-agent-k8smon
      hostNetwork: true
      # 'hostPID: true' enables the Elastic Security integration to observe all process exec events on the host.
      # Sharing the host process ID namespace gives visibility of all processes running on the same host.
      hostPID: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: elastic-agent-k8smon
        image: docker.elastic.co/beats/elastic-agent:8.6.2
        env:
        - name: FLEET_ENROLL
          value: "1"
        - name: FLEET_INSECURE
          value: "false"
        - name: FLEET_URL
          valueFrom:
            secretKeyRef:
              name: fleet-elsec5-k8smon
              key: url
        - name: FLEET_ENROLLMENT_TOKEN
          valueFrom:
            secretKeyRef:
              name: fleet-elsec5-k8smon
              key: token
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        securityContext:
          runAsUser: 0
          capabilities:
            add:
              # The following capabilities are needed for 'Defend for containers' integration (cloud-defend)
              # If you are not using this integration, then these capabilites can be removed.
              - BPF # (since Linux 5.8) allows loading of BPF programs, create most map types, load BTF, iterate programs and maps.
              - PERFMON # (since Linux 5.8) allows attaching of BPF programs used for performance metrics and observability operations.
              - SYS_RESOURCE # Allow use of special resources or raising of resource limits. Used by 'Defend for Containers' to modify 'rlimit_memlock'
        resources:
          limits:
            memory: 700Mi
          requests:
            cpu: 100m
            memory: 400Mi
        volumeMounts:
          - name: proc
            mountPath: /hostfs/proc
            readOnly: true
          - name: cgroup
            mountPath: /hostfs/sys/fs/cgroup
            readOnly: true
          - name: varlibdockercontainers
            mountPath: /var/lib/docker/containers
            readOnly: true
          - name: varlog
            mountPath: /var/log
            readOnly: true
          - name: etc-full
            mountPath: /hostfs/etc
            readOnly: true
          - name: var-lib
            mountPath: /hostfs/var/lib
            readOnly: true
          - name: etc-mid
            mountPath: /etc/machine-id
            readOnly: true
          - name: sys-kernel-debug
            mountPath: /sys/kernel/debug
          - name: elastic-agent-k8smon
            mountPath: "/usr/share/elastic-agent/state"
      volumes:
        - name: proc
          hostPath:
            path: /proc
        - name: cgroup
          hostPath:
            path: /sys/fs/cgroup
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
        - name: varlog
          hostPath:
            path: /var/log
        # The following volumes are needed for Cloud Security Posture integration (cloudbeat)
        # If you are not using this integration, then these volumes and the corresponding
        # mounts can be removed.
        - name: etc-full
          hostPath:
            path: /etc
        - name: var-lib
          hostPath:
            path: /var/lib
        # Mount /etc/machine-id from the host to determine host ID
        # Needed for Elastic Security integration
        - name: etc-mid
          hostPath:
            path: /etc/machine-id
            type: File
        # Needed for 'Defend for containers' integration (cloud-defend)
        # If you are not using this integration, then these volumes and the corresponding
        # mounts can be removed.
        - name: sys-kernel-debug
          hostPath:
            path: /sys/kernel/debug
        - name: elastic-agent-k8smon
          hostPath:
            path: /var/local/elastic-agent-k8smon
            type: DirectoryOrCreate
```
(NB: I used namespace "monitoring" as I wanted to stay out of kube-system)

We can't use PVC as:
 - we need to create one per node, and DaemonSet does not support PVC templates; or
 - we'd need a ReadWriteMany with "subpath:" set, but that would require the k8s admin have storage of that type

Therefore I (ab)used HostPath.

What is the official guidance? can we update our docs to comment on this?

**Comment by ThorbenJ** [comment]
Hi all, in order to support a customer (who I know is watching this issue) I've gone further down the rabbit hole...

# 2 (of 2):

We document deploying Agent on k8s as a DaemonSet (in both its own docs and in ECK docs) in order to monitor k8s itself. However as pointed out initially in this issue, that is not always what one wants to do. There is also the common use case of wanting to host agent in k8s to run integrations, such as that received remote data.
e.g.
- Azure Event Hub (M365 Defender, etc)
- Threat intelligence (MISP, Recorded Future, etc)
- Syslog receivers

My original attempt (at the top of this issue) was to use a Deployment, however this cannot be safe scaled to replicas more than 1, yet we've seen Azure Event Hub ingestions (for example) may need multiple agents to keep with the expected load.

As such here is a possible StatefulSet configuration:
```
# kate: replace-tabs on; indent-width 2; tab-width 8; indent-mode: normal; show-tabs on;
---
# Dummy service to keep StatefulSet happy
apiVersion: v1
kind: Service
metadata:
  name: elastic-agent-delta
  labels:
    app: elastic-agent-delta
spec:
  clusterIP: None
  selector:
    app: elastic-agent-delta
---
# Using StatefulSet to keep agent state and allow scaling the number of agents
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: elastic-agent-delta
  name: elastic-agent-delta
  namespace: tj-fleet
spec:
  replicas: 1
  serviceName: elastic-agent-delta
  selector:
    matchLabels:
      app: elastic-agent-delta
  template:
    metadata:
      labels:
        app: elastic-agent-delta
    spec:
      securityContext:
        runAsUser: 0
        runAsGroup: 0
      containers:
      - name: elastic-agent-delta
        image: docker.elastic.co/beats/elastic-agent:8.6.2
        resources:
          limits:
            memory: 700Mi
          requests:
            cpu: 100m
            memory: 400Mi
        env:
        - name: FLEET_ENROLL
          value: "1"
        - name: FLEET_INSECURE
          value: "false"
        - name: FLEET_URL
          valueFrom:
            secretKeyRef:
              name: fleet-elsec5-basic
              key: url
        - name: FLEET_ENROLLMENT_TOKEN
          valueFrom:
            secretKeyRef:
              name: fleet-elsec5-basic
              key: token
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        volumeMounts:
        - name: elastic-agent-delta
          mountPath: "/usr/share/elastic-agent/state"
  volumeClaimTemplates:
  - metadata:
      name: elastic-agent-delta
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: standard-rwo
      resources:
        requests:
          storage: 128Mi
# Create secret
# kcn create secret generic fleet-elsec5 --from-literal=url="<URL>>" --from-literal=token="<TOKEN>"
# Duplicate
# for l in beta gamma epsilon zeta ; do sed -e "s/-delta/-$l/g" < agent_delta.yaml > agent_$l.yaml ; done
```

Again I am posting this here as a basis for discussion and consensus.
