### ISSUE TITLE
[REQUEST] - Add documentation for using performance counters

### ISSUE THREAD

**Issue by VihasMakwana** [elastic/ingest-docs#1650]
### Description

This feature is effective from metricbeat version 8.17.1 and 8.16.3 onwards.

### How to use this feature?

You can enable it like following:
```yaml
metricbeat.modules:

#-------------------------------- System Module --------------------------------
- module: system
  period: 30s
  use_performance_counters: true
  metricsets:
    - cpu
  enabled: true
  cpu.metrics:
    - normalized_percentages
    - percentages
```

FAQ:
Q. Are there any impact of enabling this feature on non-windows OSes?
- No. This feature is only effective for windows. For other OSes, it is a no-op

Q. What if we enable this feature on machines with less than 64 cores?
- If you enable this on machine with fewer than 64 cores on Windows, it would again behave in the same way as before.

### Resources

Relevant PR: https://github.com/elastic/beats/pull/41965
Issue: https://github.com/elastic/beats/issues/40926

### Collaboration

The documentation team will investigate the issue and create the initial content.

### Point of contact.

**Main contact:** @VihasMakwana

**Stakeholders:**  @nimarezainia @flexitrev @jlind23 @cmacknz
