### ISSUE TITLE
[REQUEST]: Make recommendation for `add_fields` as a means to support complex dynamic Kafka topics more prominent

### ISSUE THREAD

**Issue by kpollich** [elastic/ingest-docs#1780]
### Description

We currently document the ability to use the `add_fields` processor to set a complex, interpolated dynamic topic value for outputting Elastic Agent data to Kafka here: https://www.elastic.co/docs/reference/fleet/kafka-output-settings#_topics_settings. 

We should flesh this out with a specific example and a more explicit recommendation to use this behavior if the user requires a complex dynamic topic value. 

### Resources

https://www.elastic.co/docs/reference/fleet/kafka-output-settings#_topics_settings

### Collaboration

The product team will provide the initial content.

### Point of contact.

**Main contact:** @kpollich 

**Stakeholders:** @elastic/fleet @elastic/elastic-agent-control-plane @strawgate @nimarezainia

**Comment by kpollich** [comment]
Processor example (needs review):

```yml
- add_fields: 
  target: ''
  fields: 
    kafka_topic: '${data_stream.type}-${data_stream.dataset}-${data_stream.namespace}
```

The proposed workflow here would be to add the block above to any integration policies on agents that output to Kafka based on https://www.elastic.co/docs/reference/fleet/agent-processors.
