### ISSUE TITLE
[Fleet] Update doc for preconfiguration

### ISSUE THREAD

**Issue by nchaulet** [elastic/ingest-docs#191]

**Comment by jen-huang** [comment]
FYI @karenzone, just transferred this one here.

**Comment by kilfoyle** [comment]
Hi @nchaulet 

I'd like to add these missing settings to the docs but I'll need some help.

We added the `is_default_monitoring` setting already via https://github.com/elastic/kibana/pull/154247

For the other settings `xpack.fleet.fleetServerHosts` and `xpack.fleet.proxy` can you help me with:

 - a description of what each setting is
 - where I can find the required and optional parameters

I tried looking in the [Fleet API docs](https://www.elastic.co/guide/en/fleet/master/fleet-apis.html) and I also searched through the code in the Kibana repo, but I was a bit lost. :-)

**Comment by nchaulet** [comment]
Hi @kilfoyle  (here is the schema we use for the config  of preconfigured object not obvious to find and neither to read https://github.com/nchaulet/kibana/blob/2dd3a8faf266a8d88e4955cd7dcbe7e3b8f25bb7/x-pack/plugins/fleet/server/types/models/preconfiguration.ts#L89-L116)

for the `xpack.fleet.fleetServerHosts`  we accept an array of object with the following properties
```
required:
 id: string; // an unique id
 name: string;  // A name for the UI
 host_urls: string array;  // an array of https url 

optionnal:    
  is_default: boolean; // if it's the default fleet server host
  proxy_id: string; // the proxy to use with that fleet server host
```

for `xpack.fleet.proxy` we accept an array of object with the following properties
```
required:
  id: string;
  name:string;
  url: string // the proxy url

optionnal:
    proxy_headers: object [key string, value string] a map of headers to use with the proxy
    certificate_authorities: string;
    certificate: string;
    certificate_key: string;
```

we also support the `proxy_id` for output that allow to use a proxy with an output

Let me know if you have more questions
