### ISSUE TITLE
`connection_idle_timeout` setting missing from standalone and fleet-managed agent docs

### ISSUE THREAD

**Issue by kilfoyle** [elastic/ingest-docs#878]
This is a performance tuning setting that should appear in both the standalone and Fleet-managed list of settings for the Agent Elasticsearch output.

Sample agent config file from Fleet 8.12.0 (note that some settings have prefixes added for 8.12.1).
```
    id: ae050009-40b8-437f-95ce-93010ad5910a
revision: 6
outputs:
  a1803e62-1979-4609-ad6a-fe0ec7299794:
    type: elasticsearch
    bulk_max_size: 1600
    worker: 1
    queue.mem.events: 3200
    queue.mem.flush.min_events: 1600
    queue.mem.flush.timeout: 10s
    compression_level: 1
    connection_idle_timeout: 3s
    hosts:
      - 'http://localhost:9200'
    username: '${ES_USERNAME}'
    password: '${ES_PASSWORD}'
    preset: custom
  default:
    type: elasticsearch
    hosts:
      - 'https://95bcf2d63970461fab4201b9490dfb89.us-central1.gcp.cloud.es.io:443'
    username: '${ES_USERNAME}'
    password: '${ES_PASSWORD}'
    preset: balanced
```
