### ISSUE TITLE
Add performance tuning presets to standalone agent docs

### ISSUE THREAD

**Issue by kilfoyle** [elastic/ingest-docs#879]
The Fleet-managed agent Elasticsearch output settings page includes [Performance tuning presets](https://www.elastic.co/guide/en/fleet/current/es-output-settings.html#es-agent-performance-tuning).

These need to be added to the standalone agent docs as well.

I think we can just link to the two tables in the Fleet-managed versions, showing the set of default values and the testing results.

```
outputs:
  a1803e62-1979-4609-ad6a-fe0ec7299794:
    type: elasticsearch
    hosts:
      - 'http://localhost:9200'
    username: '${ES_USERNAME}'
    password: '${ES_PASSWORD}'
    preset: balanced
```
```
    preset: throughput
```

```
   preset: scale
```

```
    preset: latency
```

Example `custom` configuration:

```
id: ae050009-40b8-437f-95ce-93010ad5910a
revision: 6
outputs:
  a1803e62-1979-4609-ad6a-fe0ec7299794:
    type: elasticsearch
    bulk_max_size: 1600
    worker: 1
    queue.mem.events: 3200
    queue.mem.flush.min_events: 1600
    queue.mem.flush.timeout: 10s
    compression_level: 1
    connection_idle_timeout: 3s
    hosts:
      - 'http://localhost:9200'
    username: '${ES_USERNAME}'
    password: '${ES_PASSWORD}'
    preset: custom
  default:
    type: elasticsearch
    hosts:
      - 'https://95bcf2d63970461fab4201b9490dfb89.us-central1.gcp.cloud.es.io:443'
    username: '${ES_USERNAME}'
    password: '${ES_PASSWORD}'
    preset: balanced
```

Note that the `connection_idle_timeout` setting is not documented so I've opened a separate issue: https://github.com/elastic/ingest-docs/issues/878
